### ISSUE TITLE
PEP 8 Code Format Compliance

### ISSUE THREAD

**Issue by ArikVhedrovix** [Deep-Phield-Softworks/XeroSum#66]
Here is the link to the PEP 8 page.
https://www.python.org/dev/peps/pep-0008/
More importantly perhaps, here is a link to an automated tool to check PEP 8.
https://pypi.python.org/pypi/pep8
Also here is the link to the docstring page which is a similar subject.
https://www.python.org/dev/peps/pep-0257/

**Comment by CToups** [comment]
Thursday night May 21st, aoe.py, chunk.py, coordinate.py and dmap.py are cleaned.

*Note to Eric*:
As you go through each and every file, search for the word 'PEP8'. You'll see comments I've written where there were certain PEP8 suggestions that I couldn't implement because they either couldn't be or I didn't trust myself not to mess up something I hadn't written to begin with. These are for your consideration. Delete the comments as you go.

**Comment by EricFedrowisch** [comment]
All code currently passes the pep8 automatic checker. Closing this issue with the understanding that we will check all code for pep8 compliance before pushing it. Good job everyone!
